import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useEffect } from 'react'
import io from 'socket.io-client'
let socket: any;

const Home: NextPage = () => {
  const [clicks, setClicks] = useState(0);

  const socketInitializer = async () => {
    await fetch('/api/socket')
    socket = io()

    socket.on('connect', () => {
      console.log('connected')
      socket.on('update-click', (clicks: number) => {
        console.log(clicks);
        setClicks(clicks)
      })
    })
  }

  const countInitializer = async () => {
    const data = await (await fetch('/api/fetch')).json();
    setClicks(Number(data.clicks));
  }

  useEffect(() => {
    socketInitializer()
    countInitializer()
  }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        <button onClick={(() => {
          socket.emit('click')
        })} className="px-2 py-1 border border-gray-400 bg-gray-200 rounded-md">{clicks}</button>
      </main>
    </>
  );
};

export default Home;